version: "3.8"
services:
  back:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "${BACK_PORT}:3000"

  front:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:3000"
