export enum IQuestionType {
  MULTIPLE_CHOICES = 'MULTIPLE_CHOICES',
  MATCHING = 'MATCHING',
  WORD_CLOUD = 'WORD_CLOUD',
  UNIQUE_CHOICES = 'UNIQUE_CHOICES',
  BOOLEAN_CHOICES = 'BOOLEAN_CHOICES',
}
