export enum IWebsocketType {
  JOIN = "JOIN",
  ERROR = "ERROR",
  MEMBERS = "MEMBERS",
  STATUS = "STATUS",
  START = "START",
  ANSWER = "ANSWER",
  DISPLAY_ANSWER = "DISPLAY_ANSWER",
  NEXT_PHASE = "NEXT_PHASE",
  QUESTION_DATA = "QUESTION_DATA",
  RESULTS = "RESULTS",
  RANKING = "RANKING",
  TIMER = "TIMER",
}
