export enum QuestionType {
  MULTIPLE_CHOICES = "MULTIPLE_CHOICES",
  UNIQUE_CHOICES = "UNIQUE_CHOICES",
  BOOLEAN_CHOICES = "BOOLEAN_CHOICES",
  WORD_CLOUD = "WORD_CLOUD",
  MATCHING = "MATCHING",
}
