export enum IGameStatus {
  NOT_STARTED = 'NOT_STARTED',
  DISPLAY_QUESTION = 'DISPLAY_QUESTION',
  DISPLAY_ANSWERS = 'DISPLAY_ANSWERS',
  DISPLAY_RANKING = 'DISPLAY_RANKING',
  FINISHED = 'FINISHED',
}
