export enum IWebsocketEvent {
  JOIN = 'JOIN',
  CONNECT = 'connect',
  START = 'START',
  STATUS = 'STATUS',
  MEMBERS = 'MEMBERS',
  ERROR = 'ERROR',
  QUESTION_DATA = 'QUESTION_DATA',
  TIMER = 'TIMER',
  ANSWER = 'ANSWER',
  DISPLAY_ANSWER = 'DISPLAY_ANSWER',
  RESULTS = 'RESULTS',
}
