name: CI - Motismo

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  backend-tests:
    name: Tests Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache des dépendances Backend
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install et build (Backend)
        working-directory: backend
        run: |
          npm ci
          npm run build

      - name: Lint Backend
        working-directory: backend
        run: npm run lint

      - name: Tests unitaires & e2e (Backend)
        working-directory: backend
        run: npm run test -- --runInBand

  frontend-tests:
    name: Tests Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache des dépendances Frontend
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install (Frontend)
        working-directory: frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: frontend
        run: npm run lint

      - name: Tests unitaires (Frontend)
        working-directory: frontend
        run: npm run test -- --ci --coverage=false
